# Generated by Django 5.0.3 on 2024-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('answer', models.CharField(max_length=255, verbose_name='정답')),
                ('mid', models.CharField(max_length=255, verbose_name='범주')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('type', models.IntegerField(choices=[(1, '타입1'), (2, '타입2'), (3, '타입3')], verbose_name='타입')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
