# Generated by Django 5.0.3 on 2024-03-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('1', '타입1'), ('2', '타입2'), ('3', '타입3')], max_length=10, verbose_name='타입'),
        ),
    ]
