# Generated by Django 5.0.3 on 2024-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashHistories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashhistory',
            name='status',
            field=models.IntegerField(choices=[(1, '정답'), (0, '오답')], default=0, verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='cashhistory',
            name='submittedAnswer',
            field=models.CharField(max_length=255, null=True, verbose_name='제출정답'),
        ),
    ]
